version: "3"
services:
    weather:
      build: .
      container_name: weather
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://dockerdb:5432/mb
      ports:
        - "8082:8082"
      restart: always
      depends_on:
        - dockerdb
    dockerdb:
      image: postgres
      container_name: dockerdb
      environment:
        - POSTGRES_USER=rotar
        - POSTGRES_PASSWORD=erutus91
        - POSTGRES_DB=mb
        - PGDATA=/var/lib/postgresql/data/mb
      ports:
        - "5001:5432"
      volumes:
          - ./var/lib/postgresql/data
          - ./createdb.sh:/docker-entrypoint-initdb.d/create_CREATE SEQUENCE hibernate_sequence START 1;createdb.sh
      restart: always


